/********************************************************************
* linkdefs.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error linkdefs.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablelinkdefs();
extern void G__cpp_setup_inheritancelinkdefs();
extern void G__cpp_setup_typetablelinkdefs();
extern void G__cpp_setup_memvarlinkdefs();
extern void G__cpp_setup_globallinkdefs();
extern void G__cpp_setup_memfunclinkdefs();
extern void G__cpp_setup_funclinkdefs();
extern void G__set_cpp_environmentlinkdefs();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__linkdefsLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__linkdefsLN_vectorlEintcOallocatorlEintgRsPgRcLcLiterator;
extern G__linked_taginfo G__linkdefsLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__linkdefsLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__linkdefsLN_vectorlEfloatcOallocatorlEfloatgRsPgRcLcLiterator;
extern G__linked_taginfo G__linkdefsLN_reverse_iteratorlEvectorlEfloatcOallocatorlEfloatgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__linkdefsLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__linkdefsLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<int,allocator<int> > G__vectorlEintcOallocatorlEintgRsPgR;
typedef vector<float,allocator<float> > G__vectorlEfloatcOallocatorlEfloatgRsPgR;
